from app.pipeline.context import PipelineContext
from app.pipeline.document import Document
from app.pipeline.elements.font import FontResource
from app.pipeline.elements.page import Page
from app.pipeline.outputs.base import OutputPlugin
from app.pipeline.outputs.font_naming import css_family_name, css_weight
from app.pipeline.rendering.render_tree import build_render_tree
from app.pipeline.rendering.tree_validator import validate_render_tree
from app.services.storage_service import StorageService

_FONT_FORMAT_BY_EXT = {
    "ttf": "truetype",
    "otf": "opentype",
    "woff": "woff",
    "woff2": "woff2",
}


def _font_face_rule(font: FontResource) -> str | None:
    if not font.filename:
        return None
    ext = font.filename.rsplit(".", 1)[-1].lower()
    fmt = _FONT_FORMAT_BY_EXT.get(ext, "truetype")
    style = "italic" if font.style == "italic" else "normal"
    # Relative from resources/css/ (where this file lives) to resources/fonts/.
    return (
        f"@font-face {{\n"
        f'  font-family: "{css_family_name(font)}";\n'
        f'  src: url("../fonts/{font.filename}") format("{fmt}");\n'
        f"  font-weight: {css_weight(font)};\n"
        f"  font-style: {style};\n"
        f"}}"
    )


def _build_common_css(document: Document) -> str:
    lines = [
        "/* Generated by LayoutForge — shared rules reused across every page. */",
        # Reset the UA body margin so .lf-page sits at (0,0) — the page's
        # absolute coordinates are page-space, and any body offset (default
        # 8px) would shift the whole overlay off the background raster.
        "html, body { margin: 0; padding: 0; }",
        ".lf-page { position: relative; overflow: hidden; background-color: #ffffff; }",
        ".lf-page-background { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; }",
        # Line-as-absolute-primitive (2026-07-15b): exactly ONE absolute
        # anchor per region (`.lf-region`); `.lf-paragraph` stays
        # position:static deliberately — that's what lets its `.lf-line`
        # children's `position:absolute` `left`/`top` resolve against the
        # REGION (the nearest positioned ancestor), not against the
        # paragraph. A paragraph is a purely semantic container: it never
        # flows or positions text, only carries typography defaults its
        # lines/runs inherit.
        #
        # This replaced a flow-chain model where paragraphs/lines were
        # positioned by margin-top computed from a PDF-measured gap plus a
        # predicted sibling height — found, on a real book, to compound: a
        # paragraph whose line mixed two font sizes rendered taller than
        # its predicted height, and every paragraph after it inherited that
        # error, reaching +16.6px by the third paragraph on a cover page.
        # Absolute per-line positioning (`top`/`left` computed directly
        # from each line's own PDF `baseline_y`/`bbox.x` — see
        # render_tree.py's `_build_line_nodes`/`_line_offset`) makes that
        # structurally impossible: no line's position depends on any other
        # line's or paragraph's rendered size, so an error on one line
        # cannot propagate to another.
        # `white-space: pre` stays on `.lf-line` — forced no-browser-
        # wrapping is correct and unrelated to this change. Kerning/
        # ligatures disabled so the browser's advance model matches the
        # measurement engine's.
        ".lf-region { position: absolute; }",
        ".lf-paragraph { position: static; margin: 0; font-kerning: none; font-variant-ligatures: none; }",
        ".lf-line { position: absolute; white-space: pre; }",
        ".lf-image { position: absolute; transform-origin: top left; }",
        "",
    ]
    # Rendering Stabilization phase (temporary): the Style Registry is
    # bypassed — every paragraph/run carries a COMPLETE inline style (see
    # html_compiler.py), so no dedup classes/rules are emitted here.
    # One @font-face per FontResource — css_family_name gives every
    # extracted font file its own unique family, so two subsets of the same
    # typeface can never shadow each other (each text run loads exactly the
    # file it was extracted with; see font_naming.py).
    for font in document.fonts:
        rule = _font_face_rule(font)
        if rule:
            lines.append(rule)
            lines.append("")
    return "\n".join(lines)


def _build_page_css(page: Page, fonts_by_id: dict[str, FontResource]) -> str:
    # RIL: text geometry/style now come from the Render Tree (inline geometry
    # + Style Registry classes in common.css) — per-block #tb rules retired
    # with the legacy renderer. Page CSS keeps page size and image rules.
    lines = [
        f"/* Generated by LayoutForge — page {page.number}. */",
        f".lf-page-{page.number} {{ width: {page.width:g}px; height: {page.height:g}px; }}",
        "",
    ]

    for image in page.images:
        declarations = [
            f"left: {image.bbox.x:g}px",
            f"top: {image.bbox.y:g}px",
            f"width: {image.bbox.width:g}px",
            f"height: {image.bbox.height:g}px",
            f"z-index: {image.z_index}",
        ]
        if image.rotation:
            declarations.append(f"transform: rotate({image.rotation:g}deg)")
        rule_body = ";\n  ".join(declarations)
        lines.append(f"#img-{image.id} {{\n  {rule_body};\n}}")
        lines.append("")

    return "\n".join(lines)


class CssOutputPlugin(OutputPlugin):
    """Reads only the IDM and writes resources/css/common.css plus one
    resources/css/page_XXXX.css per page. Uses relative URLs (../fonts/...)
    so the project workspace is self-contained — the same files render
    identically whether opened from disk, served by the backend, or loaded
    into an iframe, with no per-renderer URL rewriting."""

    def __init__(self, storage_service: StorageService) -> None:
        self._storage = storage_service

    @property
    def name(self) -> str:
        return "css"

    def generate(self, context: PipelineContext) -> list[tuple[int, str]]:
        document = context.document
        assert document is not None, "Extraction stages must run before CssOutputPlugin"

        css_dir = self._storage.project_dir(context.project_id) / "resources" / "css"
        css_dir.mkdir(parents=True, exist_ok=True)

        # RIL: build + VALIDATE the Render Trees once here (deterministic,
        # derived — kept only in scratch for HtmlOutputPlugin, then discarded
        # with the context).
        trees: dict[int, object] = {}
        for page in document.pages:
            if page.text_blocks and not page.regions:
                raise RuntimeError(
                    f"page {page.number} has text but no reconstructed regions — "
                    "ReconstructTreeStage must run before output generation"
                )
            tree = build_render_tree(document, page)
            validate_render_tree(tree, page)  # RIL Rule 6: gate before any compiler
            trees[page.number] = tree
        context.scratch["ril_trees"] = trees

        (css_dir / "common.css").write_text(_build_common_css(document), encoding="utf-8")

        fonts_by_id = {font.id: font for font in document.fonts}
        generated: list[tuple[int, str]] = []
        for page in document.pages:
            filename = f"page_{page.number:04d}.css"
            (css_dir / filename).write_text(_build_page_css(page, fonts_by_id), encoding="utf-8")
            generated.append((page.number, f"resources/css/{filename}"))

        return generated
