import math

from app.pipeline.context import PipelineContext
from app.pipeline.document import Document
from app.pipeline.elements.font import FontResource
from app.pipeline.elements.page import Page
from app.pipeline.outputs.base import OutputPlugin
from app.pipeline.outputs.font_naming import css_family_name, css_family_stack, css_weight
from app.services.storage_service import StorageService

_FONT_FORMAT_BY_EXT = {
    "ttf": "truetype",
    "otf": "opentype",
    "woff": "woff",
    "woff2": "woff2",
}


def _font_face_rule(font: FontResource) -> str | None:
    if not font.filename:
        return None
    ext = font.filename.rsplit(".", 1)[-1].lower()
    fmt = _FONT_FORMAT_BY_EXT.get(ext, "truetype")
    style = "italic" if font.style == "italic" else "normal"
    # Relative from resources/css/ (where this file lives) to resources/fonts/.
    return (
        f"@font-face {{\n"
        f'  font-family: "{css_family_name(font)}";\n'
        f'  src: url("../fonts/{font.filename}") format("{fmt}");\n'
        f"  font-weight: {css_weight(font)};\n"
        f"  font-style: {style};\n"
        f"}}"
    )


def _build_common_css(document: Document) -> str:
    lines = [
        "/* Generated by LayoutForge — shared rules reused across every page. */",
        # Reset the UA body margin so .lf-page sits at (0,0) — the page's
        # absolute coordinates are page-space, and any body offset (default
        # 8px) would shift the whole overlay off the background raster.
        "html, body { margin: 0; padding: 0; }",
        ".lf-page { position: relative; overflow: hidden; background-color: #ffffff; }",
        ".lf-page-background { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; }",
        ".lf-text-block { position: absolute; margin: 0; white-space: nowrap; transform-origin: top left; }",
        # Word-pinned lines (typography Milestone 1): each word absolutely
        # placed at its true x within the line container; `pre` keeps
        # trailing/leading spaces from collapsing.
        ".lf-text-block[data-word-pinned='true'] { white-space: normal; }",
        ".lf-word { position: absolute; top: 0; white-space: pre; }",
        ".lf-image { position: absolute; transform-origin: top left; }",
        "",
    ]
    # One @font-face per FontResource — css_family_name gives every
    # extracted font file its own unique family, so two subsets of the same
    # typeface can never shadow each other (each text run loads exactly the
    # file it was extracted with; see font_naming.py).
    for font in document.fonts:
        rule = _font_face_rule(font)
        if rule:
            lines.append(rule)
            lines.append("")
    return "\n".join(lines)


def _build_page_css(page: Page, fonts_by_id: dict[str, FontResource]) -> str:
    lines = [
        f"/* Generated by LayoutForge — page {page.number}. */",
        f".lf-page-{page.number} {{ width: {page.width:g}px; height: {page.height:g}px; }}",
        "",
    ]

    for block in page.text_blocks:
        font = fonts_by_id.get(block.font_id) if block.font_id else None
        line_height = block.line_height or block.font_size * 1.2

        if block.rotation:
            # PDF rotates glyphs around the BASELINE START (the text
            # origin), not around a bounding-box corner — positioning the
            # rotated bbox and rotating about `top left` lands the text on
            # the wrong side (seen live: a 90° margin letter rendered left
            # of its slot). Recover the unrotated run length from the
            # axis-aligned bbox (run L along the direction, line box
            # thickness across it), place the UNROTATED line so its
            # baseline start sits on the PDF origin, then rotate about
            # exactly that point.
            theta = math.radians(block.rotation)
            cos_t, sin_t = abs(math.cos(theta)), abs(math.sin(theta))
            if cos_t >= sin_t:
                run_length = max(1.0, (block.bbox.width - line_height * sin_t) / max(cos_t, 1e-6))
            else:
                run_length = max(1.0, (block.bbox.height - line_height * cos_t) / max(sin_t, 1e-6))
            baseline = (block.ascender or 0.8) * block.font_size
            geometry = [
                f"left: {block.origin_x:g}px",
                f"top: {block.origin_y - baseline:g}px",
                f"width: {run_length:g}px",
                f"height: {line_height:g}px",
                f"transform: rotate({block.rotation:g}deg)",
                f"transform-origin: 0px {baseline:g}px",
            ]
        else:
            geometry = [
                f"left: {block.bbox.x:g}px",
                f"top: {block.bbox.y:g}px",
                f"width: {block.bbox.width:g}px",
                f"height: {block.bbox.height:g}px",
            ]

        declarations = geometry + [
            f"font-family: {css_family_stack(font)}",
            f"font-size: {block.font_size:g}px",
            f"line-height: {line_height:g}px",
            f"color: {block.color}",
            f"text-align: {block.alignment}",
            f"direction: {block.writing_direction}",
        ]
        if block.letter_spacing:
            declarations.append(f"letter-spacing: {block.letter_spacing:g}px")
        if block.word_spacing:
            declarations.append(f"word-spacing: {block.word_spacing:g}px")
        rule_body = ";\n  ".join(declarations)
        lines.append(f"#tb-{block.id} {{\n  {rule_body};\n}}")
        lines.append("")

    for image in page.images:
        declarations = [
            f"left: {image.bbox.x:g}px",
            f"top: {image.bbox.y:g}px",
            f"width: {image.bbox.width:g}px",
            f"height: {image.bbox.height:g}px",
            f"z-index: {image.z_index}",
        ]
        if image.rotation:
            declarations.append(f"transform: rotate({image.rotation:g}deg)")
        rule_body = ";\n  ".join(declarations)
        lines.append(f"#img-{image.id} {{\n  {rule_body};\n}}")
        lines.append("")

    return "\n".join(lines)


class CssOutputPlugin(OutputPlugin):
    """Reads only the IDM and writes resources/css/common.css plus one
    resources/css/page_XXXX.css per page. Uses relative URLs (../fonts/...)
    so the project workspace is self-contained — the same files render
    identically whether opened from disk, served by the backend, or loaded
    into an iframe, with no per-renderer URL rewriting."""

    def __init__(self, storage_service: StorageService) -> None:
        self._storage = storage_service

    @property
    def name(self) -> str:
        return "css"

    def generate(self, context: PipelineContext) -> list[tuple[int, str]]:
        document = context.document
        assert document is not None, "Extraction stages must run before CssOutputPlugin"

        css_dir = self._storage.project_dir(context.project_id) / "resources" / "css"
        css_dir.mkdir(parents=True, exist_ok=True)

        (css_dir / "common.css").write_text(_build_common_css(document), encoding="utf-8")

        fonts_by_id = {font.id: font for font in document.fonts}
        generated: list[tuple[int, str]] = []
        for page in document.pages:
            filename = f"page_{page.number:04d}.css"
            (css_dir / filename).write_text(_build_page_css(page, fonts_by_id), encoding="utf-8")
            generated.append((page.number, f"resources/css/{filename}"))

        return generated
